---
- name: create a normal user
  hosts: Web
  vars:
    user: inggy
  tasks:
    - name: add a regular user '{{ user }}'
      become: true
      user:
          name: '{{ user }}'
          shell: /bin/bash
          password: "{{ 'password' | password_hash('sha512') }}"
    - name: add new user to the group sudo
      user:
        name='{{ user }}'
        groups=sudo
        append=yes
        state=present
      when: ansible_distribution in ["Ubuntu"]
    - name: add new user to the group wheel
      user:
        name='{{ user }}'
        groups=wheel
        append=yes
        state=present
      when: ansible_facts['os_family'] == "Redhat"
    - name: create .ssh directory if it does not exist
      file:
        path: "/home/inggy/.ssh"
        state: directory
        group: inggy
        owner: inggy
        mode: "0755"
    - name: copy .ssh to current user dir
      become: true
      copy:
        src: "{{ ansible_env.HOME }}/.ssh"
        dest: "/home/inggy"
        group: inggy
        owner: inggy
        mode: "0644"
        remote_src: yes
    - name: switch default login to user
      become: true
      replace:
        path: "/etc/ssh/sshd_config"
        regexp: "#PermitRootLogin yes"
        replace: "PermitRootLogin no"
    - name: restart ssh
      become: true
      service:
        name: ssh
        state: restarted
      when:  ansible_distribution in ["Ubuntu"]
    - name: restart sshd
      become: true
      service:
        name: sshd
        state: restarted
      when: ansible_facts['os_family'] == "Redhat"
