---
- name: create a normal user
  hosts: all
  tasks:
    - name: add a regular user
      become: true
      user:
          name: user
          password: "{{ 'password' | password_hash('sha512') }}"
    - name: add user to sudo group
      user:
        name=user
        groups=sudo
        append=yes
        state=present
      when: ansible_distribution in ["Ubuntu"]
    - name: add user to wheel group
      user:
        name=user
        groups=wheel
        append=yes
        state=present
      when: ansible_distribution in ["Fedora"]
    - name: change user shell to bash
      become: true
      user:
        name: user
        shell: /bin/bash
    - name: create .ssh directory if it does not exist
      file:
        path: "/home/root/.ssh"
        state: directory
        mode: "0700"
      become: true
      become_method: sudo
    - name: create home directory
      file:
        path: "~/home"
        state: directory
      become: true
      become_method: sudo
      become_user: user
    - name: copy .ssh to current user dir
      become: true
      copy:
        src: /home/root/.ssh/
        dest: /home/user/home/.ssh/
        owner: user
        remote_src: yes
    - name: switch default login to user
      become: true
      replace:
        path: /etc/ssh/sshd_config
        regexp: "#PermitRootLogin yes"
        replace: "PermitRootLogin no"
    - name: restart ssh
      become: true
      service:
        name: ssh
        state: restarted
      when:  ansible_distribution in ["Ubuntu"]
    - name: restart sshd
      become: true
      service:
        name: sshd
        state: restarted
      when:  ansible_distribution in ["Fedora"] 
